# Generated by Django 4.2.30 on 2026-08-16 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_order', models.PositiveIntegerField()),
                ('source_label', models.TextField(blank=True)),
                ('prompt_text', models.TextField(blank=True)),
                ('latex_text', models.TextField(blank=True)),
                ('content_mode', models.CharField(max_length=12)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('is_past_exam', models.BooleanField(db_index=True, default=False)),
                ('exam_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('exam_variant', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ('document_id', 'question_order'),
            },
        ),
        migrations.CreateModel(
            name='QuestionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveBigIntegerField(unique=True)),
                ('filename', models.TextField()),
                ('title', models.CharField(max_length=240)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('page_count', models.PositiveIntegerField()),
                ('parser_strategy', models.CharField(blank=True, max_length=64)),
                ('relation_type', models.CharField(blank=True, max_length=32)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('source_id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveBigIntegerField(unique=True)),
                ('title', models.TextField()),
                ('normalized_title', models.TextField(blank=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('sort_order', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='drill.questiondocument')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drill.questiontopic')),
            ],
            options={
                'ordering': ('document_id', 'sort_order'),
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('done', 'Done'), ('correct', 'Correct'), ('review', 'Needs review')], default='done', max_length=12)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='drill.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveBigIntegerField(unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('asset_type', models.CharField(default='question_crop', max_length=24)),
                ('sha256', models.CharField(max_length=64)),
                ('mime_type', models.CharField(default='image/png', max_length=64)),
                ('image_data', models.BinaryField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='drill.question')),
            ],
            options={
                'ordering': ('position', 'source_id'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='drill.questiondocument'),
        ),
        migrations.AddField(
            model_name='question',
            name='similarity_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_questions', to='drill.questiontopic'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='drill.questiontopic'),
        ),
        migrations.AddIndex(
            model_name='questiontopic',
            index=models.Index(fields=['document', 'parent'], name='drill_topic_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiontopic',
            constraint=models.UniqueConstraint(fields=('document', 'sort_order'), name='drill_topic_document_order_unique'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['user', 'question'], name='drill_attempt_user_q_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['user', 'created_at'], name='drill_attempt_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='questionasset',
            index=models.Index(fields=['question', 'position'], name='drill_asset_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionasset',
            constraint=models.UniqueConstraint(fields=('question', 'sha256'), name='drill_question_asset_hash_unique'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['document', 'question_order'], name='drill_question_order_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['similarity_topic', 'question_order'], name='drill_question_similar_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('document', 'question_order'), name='drill_question_document_order_unique'),
        ),
    ]
