# Generated by Django 4.2.30 on 2026-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0006_questionattempt_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_source',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
