# Generated by Django 4.2.30 on 2026-08-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0007_question_answer_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic_classification_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='topic_classification_source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_category',
            field=models.CharField(choices=[('past_exam', 'Past exam'), ('adapted_exam', 'Adapted past exam'), ('mock_exam', 'Mock paper'), ('workbook', 'Workbook'), ('competition', 'Competition'), ('other_practice', 'Other practice'), ('unclassified', 'Unclassified')], db_index=True, default='unclassified', max_length=20),
        ),
    ]
