# Generated by Django 4.2.30 on 2026-09-04 19:26

from django.db import migrations, models


def populate_subject(apps, schema_editor):
    Question = apps.get_model('drill', 'Question')
    Question.objects.filter(document__workspace='drill').update(subject='math2')
    Question.objects.filter(document__workspace='ei').update(subject='ei')


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0011_question_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='estimated_time_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('unknown', 'Unclassified'), ('single_choice', 'Single choice'), ('fill_blank', 'Fill in the blank'), ('solution', 'Solution')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type_human_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type_source',
            field=models.CharField(blank=True, choices=[('', 'Not classified'), ('rule', 'Rule-assisted batch'), ('agent', 'Agent batch'), ('human', 'Human verified'), ('import', 'Source metadata')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, choices=[('math2', 'Mathematics II'), ('ei', 'Electronic information'), ('other', 'Other')], db_index=True, default='', max_length=16),
        ),
        migrations.RunPython(populate_subject, migrations.RunPython.noop),
    ]
