# Generated by Django 4.2.30 on 2026-09-04 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_math2_blueprints(apps, schema_editor):
    Blueprint = apps.get_model('drill', 'ExamBlueprint')
    Section = apps.get_model('drill', 'ExamBlueprintSection')
    definitions = [
        {
            'code': 'math2-2027-standard-v1', 'title': 'Math II 2027 · Standard Mock',
            'mode': 'standard', 'duration_minutes': 180, 'total_score': 150,
            'cooldown_days': 30,
            'sections': [
                ('Single choice', 'single_choice', 10, '5.00', 2),
                ('Fill in the blank', 'fill_blank', 6, '5.00', 2),
                ('Solutions A', 'solution', 2, '11.00', 1),
                ('Solutions B', 'solution', 4, '12.00', 2),
            ],
        },
        {
            'code': 'math2-2027-intensive-v1', 'title': 'Math II · Intensive',
            'mode': 'intensive', 'duration_minutes': 120, 'total_score': 120,
            'cooldown_days': 21,
            'sections': [
                ('Single choice', 'single_choice', 8, '5.00', 2),
                ('Fill in the blank', 'fill_blank', 4, '5.00', 2),
                ('Solutions', 'solution', 5, '12.00', 2),
            ],
        },
        {
            'code': 'math2-2027-weak-v1', 'title': 'Math II · Weak-point Training',
            'mode': 'weak', 'duration_minutes': 90, 'total_score': 90,
            'cooldown_days': 14,
            'sections': [
                ('Single choice', 'single_choice', 6, '5.00', 2),
                ('Fill in the blank', 'fill_blank', 3, '5.00', 2),
                ('Solutions', 'solution', 3, '15.00', 2),
            ],
        },
    ]
    for definition in definitions:
        sections = definition.pop('sections')
        blueprint = Blueprint.objects.create(subject='math2', version=1, **definition)
        Section.objects.bulk_create([
            Section(
                blueprint=blueprint, order=index, title=title,
                question_type=question_type, question_count=count,
                score_per_question=score, max_per_topic=max_per_topic,
            )
            for index, (title, question_type, count, score, max_per_topic)
            in enumerate(sections, 1)
        ])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drill', '0012_question_exam_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subject', models.CharField(choices=[('math2', 'Mathematics II'), ('ei', 'Electronic information'), ('other', 'Other')], db_index=True, max_length=16)),
                ('mode', models.CharField(choices=[('standard', 'Standard mock'), ('intensive', 'Intensive'), ('weak', 'Weak-point training')], db_index=True, max_length=16)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('total_score', models.PositiveSmallIntegerField()),
                ('cooldown_days', models.PositiveSmallIntegerField(default=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('subject', 'mode', '-version'),
            },
        ),
        migrations.CreateModel(
            name='ExamBlueprintSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('question_type', models.CharField(choices=[('unknown', 'Unclassified'), ('single_choice', 'Single choice'), ('fill_blank', 'Fill in the blank'), ('solution', 'Solution')], max_length=20)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('score_per_question', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chapter_weights', models.JSONField(blank=True, default=dict)),
                ('difficulty_weights', models.JSONField(blank=True, default=dict)),
                ('max_per_topic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='drill.examblueprint')),
            ],
            options={
                'ordering': ('blueprint_id', 'order'),
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seed', models.PositiveBigIntegerField()),
                ('mode', models.CharField(choices=[('standard', 'Standard mock'), ('intensive', 'Intensive'), ('weak', 'Weak-point training')], max_length=16)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('in_progress', 'In progress'), ('completed', 'Completed')], db_index=True, default='generated', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='drill.examblueprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ExamPaperItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selected_fingerprint', models.CharField(max_length=64)),
                ('user_answer', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('unanswered', 'Unanswered'), ('correct', 'Correct'), ('incorrect', 'Incorrect'), ('review', 'Needs review')], db_index=True, default='unanswered', max_length=16)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drill.exampaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_items', to='drill.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drill.examblueprintsection')),
            ],
            options={
                'ordering': ('paper_id', 'position'),
            },
        ),
        migrations.AddConstraint(
            model_name='examblueprint',
            constraint=models.UniqueConstraint(fields=('subject', 'mode', 'version'), name='drill_blueprint_subject_mode_version_unique'),
        ),
        migrations.AddIndex(
            model_name='exampaperitem',
            index=models.Index(fields=['paper', 'position'], name='drill_paper_item_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='exampaperitem',
            constraint=models.UniqueConstraint(fields=('paper', 'position'), name='drill_paper_item_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='exampaperitem',
            constraint=models.UniqueConstraint(fields=('paper', 'question'), name='drill_paper_item_question_unique'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['user', 'created_at'], name='drill_paper_user_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='examblueprintsection',
            constraint=models.UniqueConstraint(fields=('blueprint', 'order'), name='drill_blueprint_section_order_unique'),
        ),
        migrations.RunPython(seed_math2_blueprints, migrations.RunPython.noop),
    ]
