# Generated by Django 4.2.30 on 2026-09-05 04:09

import hashlib
import json

from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_paper_revisions(apps, schema_editor):
    Question = apps.get_model('drill', 'Question')
    QuestionAsset = apps.get_model('drill', 'QuestionAsset')
    QuestionRevision = apps.get_model('drill', 'QuestionRevision')
    QuestionRevisionAsset = apps.get_model('drill', 'QuestionRevisionAsset')
    ExamPaperItem = apps.get_model('drill', 'ExamPaperItem')
    question_ids = list(ExamPaperItem.objects.order_by().values_list(
        'question_id', flat=True,
    ).distinct())
    for question in Question.objects.filter(pk__in=question_ids).select_related(
        'document', 'similarity_topic', 'topic',
    ).iterator(chunk_size=100):
        assets = list(QuestionAsset.objects.filter(question_id=question.pk).order_by(
            'asset_type', 'position', 'pk',
        ))
        topic = question.similarity_topic or question.topic
        values = {
            'document_title': question.document.display_title or question.document.title,
            'topic_title': (topic.display_title or topic.title) if topic else '',
            'source_label': question.source_label,
            'display_label': question.display_label,
            'prompt_text': question.prompt_text,
            'latex_text': question.latex_text,
            'content_mode': question.content_mode,
            'question_type': question.question_type,
            'source_category': question.source_category,
            'exam_year': question.exam_year,
            'exam_variant': question.exam_variant,
            'difficulty': question.difficulty,
            'estimated_time_minutes': question.estimated_time_minutes,
            'answer_markdown': question.answer_markdown,
            'answer_source': question.answer_source,
            'answer_confidence': question.answer_confidence,
        }
        payload = {
            **values,
            'assets': [
                [asset.pk, asset.sha256, asset.asset_type, asset.position]
                for asset in assets
            ],
        }
        content_hash = hashlib.sha256(json.dumps(
            payload, ensure_ascii=False, sort_keys=True,
            separators=(',', ':'), default=str,
        ).encode('utf-8')).hexdigest()
        revision = QuestionRevision.objects.create(
            question_id=question.pk, number=1, content_hash=content_hash, **values,
        )
        QuestionRevisionAsset.objects.bulk_create([
            QuestionRevisionAsset(
                revision_id=revision.pk, asset_id=asset.pk,
                position=asset.position, asset_type=asset.asset_type,
            )
            for asset in assets
        ])
        ExamPaperItem.objects.filter(question_id=question.pk).update(
            question_revision_id=revision.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0013_exam_blueprints_and_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('document_title', models.CharField(max_length=240)),
                ('topic_title', models.TextField(blank=True)),
                ('source_label', models.TextField(blank=True)),
                ('display_label', models.TextField(blank=True)),
                ('prompt_text', models.TextField(blank=True)),
                ('latex_text', models.TextField(blank=True)),
                ('content_mode', models.CharField(max_length=12)),
                ('question_type', models.CharField(choices=[('unknown', 'Unclassified'), ('single_choice', 'Single choice'), ('fill_blank', 'Fill in the blank'), ('solution', 'Solution')], max_length=20)),
                ('source_category', models.CharField(choices=[('past_exam', 'Past exam'), ('adapted_exam', 'Adapted past exam'), ('mock_exam', 'Mock paper'), ('workbook', 'Workbook'), ('competition', 'Competition'), ('other_practice', 'Other practice'), ('unclassified', 'Unclassified')], max_length=20)),
                ('exam_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exam_variant', models.CharField(blank=True, max_length=16)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estimated_time_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('answer_markdown', models.TextField(blank=True)),
                ('answer_source', models.CharField(blank=True, max_length=32)),
                ('answer_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('question_id', '-number'),
            },
        ),
        migrations.CreateModel(
            name='QuestionRevisionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('asset_type', models.CharField(max_length=24)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_links', to='drill.questionasset')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_assets', to='drill.questionrevision')),
            ],
            options={
                'ordering': ('revision_id', 'asset_type', 'position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='questionrevision',
            name='assets',
            field=models.ManyToManyField(related_name='question_revisions', through='drill.QuestionRevisionAsset', to='drill.questionasset'),
        ),
        migrations.AddField(
            model_name='questionrevision',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='drill.question'),
        ),
        migrations.AddField(
            model_name='exampaperitem',
            name='question_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paper_items', to='drill.questionrevision'),
        ),
        migrations.AddConstraint(
            model_name='questionrevisionasset',
            constraint=models.UniqueConstraint(fields=('revision', 'asset'), name='drill_revision_asset_unique'),
        ),
        migrations.AddIndex(
            model_name='questionrevision',
            index=models.Index(fields=['question', '-number'], name='drill_revision_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.UniqueConstraint(fields=('question', 'number'), name='drill_revision_question_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.UniqueConstraint(fields=('question', 'content_hash'), name='drill_revision_question_hash_unique'),
        ),
        migrations.RunPython(backfill_paper_revisions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exampaperitem',
            name='question_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_items', to='drill.questionrevision'),
        ),
    ]
