# Generated by Django 4.2.30 on 2026-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0018_drillloginhandoff_dashboard_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
