# Generated by Django 4.2.30 on 2026-09-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0019_question_attempt_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionuserstate',
            name='active_timing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
