<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, post } from '../lib/api'
import type { LaunchToken } from '../types'

const tokens=ref<LaunchToken[]>([]), open=ref(false), revealed=ref<LaunchToken|null>(null)
const form=reactive({name:'桌面快捷方式',subject:'math',source_label:'浏览器',max_uses:null as number|null,expires_at:null as string|null,notes:''})
async function load(){try{tokens.value=await api<LaunchToken[]>('/api/launch-tokens/')}catch(e){ElMessage.error((e as Error).message)}}
async function create(){try{const token=await post<LaunchToken>('/api/launch-tokens/',form);revealed.value=token;open.value=false;await load()}catch(e){ElMessage.error((e as Error).message)}}
async function action(token:LaunchToken,name:string){try{if(name==='delete')await ElMessageBox.confirm('删除后，这个启动地址会立即失效。','删除启动令牌？',{type:'warning'});const value=await post<LaunchToken|undefined>(`/api/launch-tokens/${token.id}/${name}/`);if(value?.raw_token)revealed.value=value;await load()}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
async function copy(){if(!revealed.value?.launch_url)return;await navigator.clipboard.writeText(revealed.value.launch_url);ElMessage.success('启动地址已复制')}
onMounted(load)
</script>

<template><div class="view-stack"><section class="page-intro"><span class="eyebrow">SYSTEM & ACCESS</span><h1>设置与数据</h1><p>管理无密码快捷启动、Passkey 和完整数据导出。</p></section><section class="settings-grid"><article class="panel settings-card"><div class="card-title"><div><span class="eyebrow">PASSKEY</span><h2>安全登录</h2></div><span class="secure-badge">WebAuthn</span></div><p>使用设备生物识别或安全密钥登录。密码登录仍作为恢复方式保留。</p><a class="el-button el-button--primary" href="/accounts/2fa/">管理 Passkey</a></article><article class="panel settings-card"><div class="card-title"><div><span class="eyebrow">PORTABLE DATA</span><h2>导出学习数据</h2></div></div><p>导出包含原始学习总结和结构化复盘字段，不做摘要截断。</p><div class="export-actions"><a href="/api/export/csv/">CSV</a><a href="/api/export/json/">JSON</a><a href="/api/export/markdown/">Markdown</a></div></article></section><section class="panel token-panel"><div class="section-heading"><div><span class="eyebrow">LAUNCH TOKENS</span><h2>快捷启动令牌</h2></div><el-button type="primary" @click="open=true">创建令牌</el-button></div><p class="section-note">令牌只允许启动指定科目，不能查看记录或访问账号。原始地址只显示一次。</p><el-empty v-if="!tokens.length" description="还没有快捷启动令牌"/><article v-for="token in tokens" :key="token.id" class="token-row"><div><strong>{{ token.name }}</strong><small>{{ token.subject }} · 已使用 {{ token.usage_count }} 次<span v-if="token.max_uses"> / {{ token.max_uses }}</span></small></div><el-tag :type="token.usable?'success':'info'">{{ token.usable?'有效':'已失效' }}</el-tag><div><el-button text @click="action(token,token.is_active?'revoke':'regenerate')">{{ token.is_active?'撤销':'重新生成' }}</el-button><el-button text type="danger" @click="action(token,'delete')">删除</el-button></div></article></section><el-dialog v-model="open" title="创建快捷启动令牌" width="min(560px,94vw)"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><div class="form-pair"><el-form-item label="固定科目"><el-select v-model="form.subject"><el-option label="数学" value="math"/><el-option label="英语" value="english"/><el-option label="专业课" value="major"/><el-option label="训练" value="training"/></el-select></el-form-item><el-form-item label="最多使用次数"><el-input-number v-model="form.max_uses" :min="1" placeholder="不限"/></el-form-item></div><el-form-item label="来源标签"><el-input v-model="form.source_label"/></el-form-item><el-form-item label="备注"><el-input v-model="form.notes" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" @click="create">创建</el-button></template></el-dialog><el-dialog :model-value="Boolean(revealed)" title="立即保存这个地址" width="min(620px,94vw)" @close="revealed=null"><el-alert title="出于安全原因，关闭后将无法再次查看原始令牌。" type="warning" :closable="false" show-icon/><div class="reveal-url">{{ revealed?.launch_url }}</div><template #footer><el-button type="primary" @click="copy">复制地址</el-button><el-button @click="revealed=null">我已保存</el-button></template></el-dialog></div></template>
