# Generated by Django 5.2.14 on 2026-05-25 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mth', '数学'), ('eng', '英语'), ('pro', '专业课'), ('cycling', '骑车'), ('swimming', '游泳'), ('gym', '力量训练'), ('running', '跑步')], max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
