# Generated by Django 5.2.14 on 2026-05-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='category',
            field=models.CharField(choices=[('mth', '数学'), ('eng', '英语'), ('pro', '专业课'), ('training', '训练')], max_length=20),
        ),
    ]
