# Generated by Django 5.0.2 on 2026-06-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_timelog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='category',
            field=models.CharField(choices=[('math', '数学'), ('english', '英语'), ('major', '专业课'), ('training', '训练')], max_length=20),
        ),
    ]
