# Generated by Django 4.2.30 on 2026-07-18

import datetime

from django.db import migrations, models
from django.utils import timezone


SHANGHAI_TIMEZONE = datetime.timezone(datetime.timedelta(hours=8))


def backfill_daily_study_stats(apps, schema_editor):
    TimeLog = apps.get_model('tracker', 'TimeLog')
    DailyStudyStat = apps.get_model('tracker', 'DailyStudyStat')

    grouped_stats = {}
    completed_logs = TimeLog.objects.filter(end_time__isnull=False).order_by(
        'start_time'
    )
    for log in completed_logs.iterator():
        start_time = log.start_time
        if timezone.is_naive(start_time):
            start_time = timezone.make_aware(start_time, SHANGHAI_TIMEZONE)
        local_start = timezone.localtime(start_time, SHANGHAI_TIMEZONE)
        study_date = local_start.date()
        stat = grouped_stats.setdefault(
            study_date,
            {
                'study_count': 0,
                'first_start_time': log.start_time,
                'total_minutes': 0,
            },
        )
        stat['study_count'] += 1
        duration_minutes = int((log.end_time - log.start_time).total_seconds() / 60)
        stat['total_minutes'] += max(0, duration_minutes)

    DailyStudyStat.objects.bulk_create(
        DailyStudyStat(date=study_date, **values)
        for study_date, values in grouped_stats.items()
    )


def clear_daily_study_stats(apps, schema_editor):
    DailyStudyStat = apps.get_model('tracker', 'DailyStudyStat')
    DailyStudyStat.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_timelog_note_alter_timelog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudyStat',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField(unique=True)),
                ('study_count', models.PositiveIntegerField(default=0)),
                ('first_start_time', models.DateTimeField()),
                ('total_minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.RunPython(backfill_daily_study_stats, clear_daily_study_stats),
    ]
