# Generated by Django 4.2.30 on 2026-08-09 04:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0006_timelog_start_time_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('math', '数学'), ('english', '英语'), ('major', '专业课'), ('training', '训练')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('importance', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mastery_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('unknown', '未知'), ('learning', '学习中'), ('understood', '已理解'), ('stable', '稳定'), ('automatic', '自动化')], default='unknown', max_length=16)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LaunchToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(choices=[('math', '数学'), ('english', '英语'), ('major', '专业课'), ('training', '训练')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LearningIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('math', '数学'), ('english', '英语'), ('major', '专业课'), ('training', '训练')], max_length=20)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('issue_type', models.CharField(choices=[('concept_error', '概念错误'), ('calculation_error', '计算错误'), ('recognition_error', '识别错误'), ('memory_error', '记忆错误'), ('speed_problem', '速度问题'), ('careless_error', '粗心错误'), ('strategy_problem', '策略问题')], max_length=24)),
                ('description', models.TextField()),
                ('solution', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('repeat_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ('-start_time',)},
        ),
        migrations.AddField(
            model_name='dailystudystat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_study_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelog',
            name='breakthrough',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='chapter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='timelog',
            name='confidence_after',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='timelog',
            name='confidence_before',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='timelog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='timelog',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='timelog',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('low', '低'), ('medium', '中'), ('high', '高')], max_length=12),
        ),
        migrations.AddField(
            model_name='timelog',
            name='focus_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='timelog',
            name='learning_mode',
            field=models.CharField(blank=True, choices=[('theory', '理论学习'), ('exercise', '练习'), ('review', '复习'), ('memorization', '记忆'), ('project', '项目'), ('exam_simulation', '模拟考试')], max_length=24),
        ),
        migrations.AddField(
            model_name='timelog',
            name='next_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='problems',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='status',
            field=models.CharField(choices=[('running', '进行中'), ('completed', '已完成'), ('abandoned', '已放弃')], default='running', max_length=16),
        ),
        migrations.AddField(
            model_name='timelog',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='timelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailystudystat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['user', 'start_time'], name='session_user_start_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['user', 'status'], name='session_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystudystat',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_stat_per_user'),
        ),
        migrations.AddConstraint(
            model_name='timelog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('user',), name='one_running_session_per_user'),
        ),
        migrations.AddField(
            model_name='learningissue',
            name='study_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='tracker.timelog'),
        ),
        migrations.AddField(
            model_name='learningissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='launchtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracker.knowledgepoint'),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='learningissue',
            index=models.Index(fields=['user', 'resolved'], name='issue_user_resolved_idx'),
        ),
        migrations.AddIndex(
            model_name='launchtoken',
            index=models.Index(fields=['user', 'is_active'], name='token_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgepoint',
            index=models.Index(fields=['user', 'category'], name='knowledge_user_cat_idx'),
        ),
    ]
