# Generated by Django 4.2.30 on 2026-08-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_backfill_session_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepoint',
            name='category',
            field=models.CharField(choices=[('math', 'Mathematics'), ('english', 'English'), ('major', 'Major'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgepoint',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('learning', 'Learning'), ('understood', 'Understood'), ('stable', 'Stable'), ('automatic', 'Automatic')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='launchtoken',
            name='category',
            field=models.CharField(choices=[('math', 'Mathematics'), ('english', 'English'), ('major', 'Major'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learningissue',
            name='category',
            field=models.CharField(choices=[('math', 'Mathematics'), ('english', 'English'), ('major', 'Major'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learningissue',
            name='issue_type',
            field=models.CharField(choices=[('concept_error', 'Concept error'), ('calculation_error', 'Calculation error'), ('recognition_error', 'Recognition error'), ('memory_error', 'Memory error'), ('speed_problem', 'Speed problem'), ('careless_error', 'Careless error'), ('strategy_problem', 'Strategy problem')], max_length=24),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='category',
            field=models.CharField(choices=[('math', 'Mathematics'), ('english', 'English'), ('major', 'Major'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=12),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='learning_mode',
            field=models.CharField(blank=True, choices=[('theory', 'Theory'), ('exercise', 'Exercise'), ('review', 'Review'), ('memorization', 'Memorization'), ('project', 'Project'), ('exam_simulation', 'Exam simulation')], max_length=24),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('abandoned', 'Legacy abandoned')], default='running', max_length=16),
        ),
    ]
