# Generated by Django 4.2.30 on 2026-08-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_note_title_add_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubNoteSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced')], db_index=True, default='pending', max_length=12)),
                ('markdown_path', models.CharField(blank=True, max_length=500)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_note_sync', to='tracker.timelog')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
