# Generated by Django 4.2.30 on 2026-08-12 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracker.encrypted_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0018_launch_windows_and_disturbances'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(default='green', max_length=16)),
                ('encrypted_content', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
            bases=(tracker.encrypted_models.EncryptedAtRestMixin, models.Model),
        ),
        migrations.AddField(
            model_name='timelog',
            name='task_path',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TaskPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('english', 'English'), ('major', 'Major'), ('training', 'Training')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('is_home_shortcut', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('encrypted_content', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tracker.taskpreset')),
                ('tags', models.ManyToManyField(blank=True, related_name='task_presets', to='tracker.studytag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('subject', 'sort_order', 'created_at'),
            },
            bases=(tracker.encrypted_models.EncryptedAtRestMixin, models.Model),
        ),
        migrations.AddField(
            model_name='timelog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='tracker.studytag'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='task_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracker.taskpreset'),
        ),
        migrations.AddIndex(
            model_name='taskpreset',
            index=models.Index(fields=['user', 'subject', 'is_active'], name='preset_user_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='taskpreset',
            index=models.Index(fields=['user', 'is_home_shortcut'], name='preset_user_home_idx'),
        ),
        migrations.AddIndex(
            model_name='studytag',
            index=models.Index(fields=['user'], name='tag_user_idx'),
        ),
    ]
